# Generated by Django 5.2.3 on 2025-06-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_alter_ingresomensual_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
