# Generated by Django 5.2.3 on 2025-06-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_alter_gastos_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajadeahorros',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
